version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - gymbro_network

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gymbro_network
      - monitoring_network

volumes:
  pgdata:

networks:
  gymbro_network:
    driver: bridge
  monitoring_network:
    external: true
